// third-app/src/App.vue
<script setup>
import { ref } from 'vue';

const count = ref(0);

const increment = () => count.value++;
const decrement = () => count.value--;
</script>

<template>
  <h1>Vue App</h1>
  <h2>Count: {{ count }}</h2>
  <button @click="increment">increment</button>
  <button @click="decrement">decrement</button>
</template>

// second-app/src/App.jsx
import React, { useState } from "react";

export const App = () => {
  const [count, setCount] = useState(0);

  return <>
    <h1>React App</h1>
    <h2>Count: {count}</h2>
    <button onClick={() => setCount(prev => prev + 1)}>increment</button>
    <button onClick={() => setCount(prev => prev - 1)}>decrement</button>
    </>
}
